/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_ButtonStates */

#ifndef _Included_com_sixense_utils_ButtonStates
#define _Included_com_sixense_utils_ButtonStates
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    create
 * Signature: ()L
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_ButtonStates_create
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    destroy
 * Signature: (L)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    update
 * Signature: (Lcom/sixense/ControllerData;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_update
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    buttonJustPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_buttonJustPressed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    buttonJustReleased
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_buttonJustReleased
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    setTriggerThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_setTriggerThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    triggerJustPressed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_triggerJustPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    triggerJustReleased
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_triggerJustReleased
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    setStickThreshold
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_setStickThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    stickJustPressed
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_stickJustPressed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    stickJustReleased
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_stickJustReleased
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    setAbsoluteTiltAngleThresholdInDeg
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_setAbsoluteTiltAngleThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    setRelativeTiltAngleThresholdInDeg
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_setRelativeTiltAngleThreshold
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    setRelativeOrigin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_setRelativeOrigin
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    startPointGesture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_startPointGesture
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    stopPointGesture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ButtonStates_stopPointGesture
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    relativeTiltJustStarted
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_relativeTiltJustStarted
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    relativeTiltJustStopped
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_relativeTiltJustStopped
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    absoluteTiltJustStarted
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_absoluteTiltJustStarted
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    absoluteTiltJustStopped
 * Signature: (Lcom/sixense/utils/enums/EnumDirection;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_absoluteTiltJustStopped
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    justStarted
 * Signature: (Lcom/sixense/utils/enums/EnumActionType;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_justStarted
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_sixense_utils_ButtonStates
 * Method:    justStopped
 * Signature: (Lcom/sixense/utils/enums/EnumActionType;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ButtonStates_justStopped
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
