/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_LaserPointer */

#ifndef _Included_com_sixense_utils_LaserPointer
#define _Included_com_sixense_utils_LaserPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_LaserPointer_create
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_LaserPointer_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    setScreenSize
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_LaserPointer_setScreenSize
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    setScreenCenterOffset
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_LaserPointer_setScreenCenterOffset
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    getScreenSize
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_LaserPointer_getScreenSize
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    getScreenCenterOffset
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_LaserPointer_getScreenCenterOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_LaserPointer
 * Method:    getIntersection
 * Signature: (FFFFFFFFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_LaserPointer_getIntersection
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
