/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_ControllerManager */

#ifndef _Included_com_sixense_utils_ControllerManager
#define _Included_com_sixense_utils_ControllerManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    setGameType
 * Signature: (Lcom/sixense/utils/EnumGameType;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ControllerManager_setGameType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    getGameType
 * Signature: ()Lcom/sixense/utils/EnumGameType;
 */
JNIEXPORT jobject JNICALL Java_com_sixense_utils_ControllerManager_getGameType
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    update
 * Signature: ([Lcom/sixense/ControllerData;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ControllerManager_update
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    getIndex
 * Signature: (Lcom/sixense/utils/EnumControllerDesc;)I
 */
JNIEXPORT jint JNICALL Java_com_sixense_utils_ControllerManager_getIndex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    rebind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ControllerManager_rebind
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    registerSetupCallback
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ControllerManager_registerSetupCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    isMenuVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ControllerManager_isMenuVisible
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    getTextureFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sixense_utils_ControllerManager_getTextureFileName
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    getStepString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sixense_utils_ControllerManager_getStepString
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    shouldPlaySound
 * Signature: ()Lcom/sixense/utils/EnumSoundType;
 */
JNIEXPORT jobject JNICALL Java_com_sixense_utils_ControllerManager_shouldPlaySound
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ControllerManager
 * Method:    getCurrentStep
 * Signature: ()Lcom/sixense/utils/EnumSetupStep;
 */
JNIEXPORT jobject JNICALL Java_com_sixense_utils_ControllerManager_getCurrentStep
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

JavaVM* jvm;
jobject cbRef;

void callback(sixenseUtils::ControllerManager::setup_step step);
#endif
