/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_FPSViewAngles */

#ifndef _Included_com_sixense_utils_FPSViewAngles
#define _Included_com_sixense_utils_FPSViewAngles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_FPSViewAngles_create
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setGame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setMode
 * Signature: (Lcom/sixense/utils/enums/EnumFPSMode;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getMode
 * Signature: ()Lcom/sixense/utils/enums/EnumFPSMode;
 */
JNIEXPORT jobject JNICALL Java_com_sixense_utils_FPSViewAngles_getMode
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    update
 * Signature: (Lcom/sixense/ControllerData;Lcom/sixense/ControllerData;F)I
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_FPSViewAngles_update
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getViewAngles
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_FPSViewAngles_getViewAngles
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getViewAngleOffset
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_FPSViewAngles_getViewAngleOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getSpinSpeed
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_FPSViewAngles_getSpinSpeed
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    forceViewAngles
 * Signature: (Lcom/sixense/utils/enums/EnumFPSMode;FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_forceViewAngles
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setFeetAnglesMetroid
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setFeetAnglesMetroid
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getFeetAnglesMetroid
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_FPSViewAngles_getFeetAnglesMetroid
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setParameter
 * Signature: (Lcom/sixense/utils/enums/EnumFPSParams;F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setParameter
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getParameter
 * Signature: (Lcom/sixense/utils/enums/EnumFPSParams;)F
 */
JNIEXPORT jfloat JNICALL Java_com_sixense_utils_FPSViewAngles_getParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setFov
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setFov
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    getFov
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_FPSViewAngles_getFov
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setHoldingTurnSpeed
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setHoldingTurnSpeed
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    setRatcheting
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_setRatcheting
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    isRatcheting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_FPSViewAngles_isRatcheting
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_FPSViewAngles
 * Method:    forceMetroidBlend
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_FPSViewAngles_forceMetroidBlend
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
