/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_Derivatives */

#ifndef _Included_com_sixense_utils_Derivatives
#define _Included_com_sixense_utils_Derivatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    create
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_Derivatives_create
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Derivatives_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    update
 * Signature: (Lcom/sixense/ControllerData;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Derivatives_update
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    getPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Derivatives_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    getVelocity
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Derivatives_getVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    getAcceleration
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Derivatives_getAcceleration
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    getRSquared
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Derivatives_getRSquared
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    setOffset
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Derivatives_setOffset
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_Derivatives
 * Method:    getOffset
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Derivatives_getOffset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
