/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_Events */

#ifndef _Included_com_sixense_utils_Events
#define _Included_com_sixense_utils_Events
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_Events
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_Events_create
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Events_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    setGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Events_setGame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sixense_utils_Events
 * Method:    setBinding
 * Signature: (Lcom/sixense/utils/enums/EnumEvent;Lcom/sixense/utils/enums/EnumController;Lcom/sixense/utils/enums/EnumActionType;I)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Events_setBinding
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_sixense_utils_Events
 * Method:    setPointGestureButton
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Events_setPointGestureButton
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sixense_utils_Events
 * Method:    isPointGestureActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_Events_isPointGestureActive
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    update
 * Signature: (Lcom/sixense/ControllerData;Lcom/sixense/ControllerData;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_Events_update
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_Events
 * Method:    eventActive
 * Signature: (Lcom/sixense/utils/enums/EnumEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_Events_eventActive
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    eventStarted
 * Signature: (Lcom/sixense/utils/enums/EnumEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_Events_eventStarted
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    eventStopped
 * Signature: (Lcom/sixense/utils/enums/EnumEvent;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_Events_eventStopped
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    getGrenadeThrowVelocity
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_Events_getGrenadeThrowVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_Events
 * Method:    setParameter
 * Signature: (Lcom/sixense/utils/enums/EnumEventParam;F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_Events_setParameter
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_Events
 * Method:    getParameter
 * Signature: (Lcom/sixense/utils/enums/EnumEventParam;)F
 */
JNIEXPORT jfloat JNICALL Java_com_sixense_utils_Events_getParameter
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
