/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sixense_utils_ViewAngles */

#ifndef _Included_com_sixense_utils_ViewAngles
#define _Included_com_sixense_utils_ViewAngles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sixense_utils_ViewAngles_create
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setGame
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setGame
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setMode
 * Signature: (Lcom/sixense/utils/enums/EnumMode;)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getMode
 * Signature: ()Lcom/sixense/utils/enums/EnumMode;
 */
JNIEXPORT jobject JNICALL Java_com_sixense_utils_ViewAngles_getMode
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    update
 * Signature: (Lcom/sixense/ControllerData;Lcom/sixense/ControllerData;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ViewAngles_update
  (JNIEnv *, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getViewAngles
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_ViewAngles_getViewAngles
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getViewAngleOffset
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_ViewAngles_getViewAngleOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getSpinSpeed
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_ViewAngles_getSpinSpeed
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    forceViewAngles
 * Signature: (Lcom/sixense/utils/enums/EnumMode;FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_forceViewAngles
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setFeetAnglesMetroid
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setFeetAnglesMetroid
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getFeetAnglesMetroid
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_ViewAngles_getFeetAnglesMetroid
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setParameter
 * Signature: (Lcom/sixense/utils/enums/EnumViewParam;F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setParameter
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getParameter
 * Signature: (Lcom/sixense/utils/enums/EnumViewParam;)F
 */
JNIEXPORT jfloat JNICALL Java_com_sixense_utils_ViewAngles_getParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setFov
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setFov
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    getFov
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_sixense_utils_ViewAngles_getFov
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setHoldingTurnSpeed
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setHoldingTurnSpeed
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    setRatcheting
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_setRatcheting
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    isRatcheting
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sixense_utils_ViewAngles_isRatcheting
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_sixense_utils_ViewAngles
 * Method:    forceMetroidBlend
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_sixense_utils_ViewAngles_forceMetroidBlend
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
