package com.sixense.utils.enums;

/**
 * @author Yoda12999
 */
public enum EnumEventParam {
    MELEE_SENSITIVITY,
    WEAPON_SELECT_SENSITIVITY,
    CROUCH_SENSITIVITY,
    JUMP_SENSITIVITY,
    RELOAD_SENSITIVITY,
    THROW_SENSITIVITY,
    CONTROLLER_ANGLE_MODE,
    AUTO_ONE_TO_ONE_START_VEL,
    AUTO_ONE_TO_ONE_START_ACCEL,
    AUTO_ONE_TO_ONE_START_ACCEL_TIMER,
    AUTO_ONE_TO_ONE_START_ANGLE_THRESH,
    AUTO_ONE_TO_ONE_STOP_XY_DIST,
    AUTO_ONE_TO_ONE_STOP_Z_DIST,
    LEFT_HANDED,
    LAST_PARAM
}
