package com.sixense.utils.enums;

/**
 * @author Yoda12999
 */
public enum EnumViewParam {
    CONTROLLER_ANGLE_MODE,

    AIM_1TO1_HEADING_MULTIPLIER,
    AIM_1TO1_PITCH_MULTIPLIER,
    AIM_1TO1_RATCHET_VERTICAL,

    AIM_METROID_HEADING_MULTIPLIER,
    AIM_METROID_PITCH_MULTIPLIER,
    AIM_METROID_DEAD_ZONE_RADIUS,
    AIM_METROID_ACCEL_BAND_SIZE,
    AIM_METROID_MAX_SPEED,
    AIM_METROID_AUTO_LEVEL_RATE,
    AIM_METROID_ACCEL_BAND_EXPONENT,
    AIM_METROID_SWITCH_BLEND_TIME_ENTER,
    AIM_METROID_SWITCH_BLEND_TIME_EXIT,

    FEET_ANGLES_OFFSET_STICK_SPIN_HORIZ_MULTIPLIER,
    FEET_ANGLES_OFFSET_STICK_SPIN_VERT_MULTIPLIER,
    FEET_ANGLES_OFFSET_STICK_SPIN_INVERT_PITCH,
    FEET_ANGLES_OFFSET_STICK_SPIN_EXPONENT,

    PITCH_CHANGE_BLEND_VAL,

    SPRING_VIEW_ENABLED,
    SPRING_VIEW_MIN_SPRING,
    SPRING_VIEW_MAX_SPRING,
    SPRING_VIEW_MIN_ANGLE,
    SPRING_VIEW_MAX_ANGLE,
    
    FEET_ANGLES_ALLOW_VERT_STICK_SPIN,

    AIM_METROID_ACCEL_BAND_POWER,

    HOLDING_TURN_SPEED,

    ROLL_CORRECTION_BLEND,
    EXIT_METROID_BLEND,

    LEFT_HANDED,

    LAST_PARAM
}
