package com.sixense.utils.enums;

/**
 * @author Yoda12999
 */
public enum EnumGameType {
    ONE_PLAYER_ONE_CONTROLLER,
    ONE_PLAYER_TWO_CONTROLLER,
    TWO_PLAYER_ONE_CONTROLLER,
    TWO_PLAYER_TWO_CONTROLLER,
    THREE_PLAYER_ONE_CONTROLLER,
    THREE_PLAYER_TWO_CONTROLLER,
    FOUR_PLAYER_ONE_CONTROLLER,
    FOUR_PLAYER_TWO_CONTROLLER
}
